name: Docker build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: false
        type: string
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 12 * * 2"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build_docker:
    name: build docker images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: noble
            ubuntu: noble
          - tag: jammy
            ubuntu: jammy
          - tag: latest
            ubuntu: noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tags
        id: tags
        run: |
          echo "Generate tags"
          if [ "${{ inputs.version }}" != '' ]; then
            version="${{ inputs.version }}"
          else
            mkdir check_version
            cd check_version
            git init
            git remote add origin https://github.com/immich-app/base-images.git
            git fetch --tags https://github.com/immich-app/base-images.git
            version=$(git describe --tags $(git rev-list --tags --max-count=1))
            cd ..
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "build_date=$(date +'%Y-%m-%dT%H:%M:%S%:z')" >> $GITHUB_OUTPUT
          echo "short_date=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/baseimage-immich
          tags: |
            ${{ github.event_name == 'pull_request' && format('pr-{0}-{1}-{2}', matrix.tag, steps.tags.outputs.short_date, steps.tags.outputs.commit) || '' }}
            ${{ github.event_name == 'pull_request' && format('pr-{0}-{1}', matrix.tag, steps.tags.outputs.short_date) || '' }}
            ${{ github.event_name != 'pull_request' && format('{0}-{1}-{2}', matrix.tag, steps.tags.outputs.short_date, steps.tags.outputs.commit) || '' }}
            ${{ github.event_name != 'pull_request' && format('{0}-{1}', matrix.tag, steps.tags.outputs.short_date) || '' }}
            ${{ github.event_name != 'pull_request' && matrix.tag == 'latest' && matrix.ubuntu == 'noble' && 'latest' || '' }}
            ${{ github.event_name != 'pull_request' && matrix.tag == 'latest' && matrix.ubuntu == 'noble' && format('{0}-{1}', steps.tags.outputs.short_date, steps.tags.outputs.commit) || '' }}
            ${{ github.event_name != 'pull_request' && matrix.tag == 'latest' && matrix.ubuntu == 'noble' && steps.tags.outputs.short_date || '' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v6
        with:
          provenance: false # prevent unknown architecture
          platforms: linux/amd64,linux/arm64
          push: ${{ !github.event.pull_request.head.repo.fork }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            BUILD_DATE=${{ steps.tags.outputs.build_date }}
            VERSION=${{ steps.tags.outputs.version }}
            CURRENT_UBUNTU_VERSION=${{ matrix.ubuntu }}
