name: Docker build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: false
        type: string
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 12 * * 2"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build_docker:
    name: build docker images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tags
        id: tags
        run: |
          echo "Generate tags"
          if [ "${{ inputs.version }}" != '' ]; then
            version="${{ inputs.version }}"
          else
            version=$(curl -sL https://api.github.com/repos/immich-app/base-images/tags | jq -r '.[0].name')
            counter=0

            # Loop until version is not "null" or counter reaches 10
            while [ $counter -lt 10 ]; do
                version=$(curl -sL https://api.github.com/repos/immich-app/base-images/tags | jq -r '.[0].name')

                # Check if version is not "null"
                if [ "$version" != "null" ]; then
                    echo "version is not null: $version"
                    break
                else
                    echo "version is still null, retrying in 10 seconds..."
                    sleep 10
                    ((counter++))
                fi
            done

            if [ "$version" = "null" ]; then
                echo "version is still null after 10 attempts, exiting..."
                exit 1
            fi
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "build_date=$(date +'%Y-%m-%dT%H:%M:%S%:z')" >> $GITHUB_OUTPUT
          echo "short_date=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/baseimage-immich
          tags: |
            type=ref,event=pr,value=${{ steps.tags.outputs.version }},enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=pr,value=${{ steps.tags.outputs.version }},enable=${{ github.event_name == 'pull_request' }},suffix=-${{ steps.tags.outputs.version }}
            type=ref,event=pr,value=${{ steps.tags.outputs.version }},enable=${{ github.event_name == 'pull_request' }},suffix=-${{ steps.tags.outputs.version }}-${{ steps.tags.outputs.commit }}
            type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }},suffix=${{ matrix.suffix }}
            type=raw,value=${{ steps.tags.outputs.version }},enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=${{ steps.tags.outputs.version }},enable=${{ github.event_name != 'pull_request' }},suffix=-${{ steps.tags.outputs.commit }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v6
        with:
          provenance: false # prevent unknown architecture
          platforms: linux/amd64,linux/arm64
          push: ${{ !github.event.pull_request.head.repo.fork }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            BUILD_DATE=${{ steps.tags.outputs.build_date }}
            VERSION=${{ steps.tags.outputs.version }}
